import { screen, fireEvent } from '@testing-library/react';
import { render, unmountComponentAtNode } from 'react-dom';
import { act } from 'react-dom/test-utils';
import FormContainer from './FormContainer';

let container = null;
beforeEach(() => {
  // setup a DOM element as a render target
  container = document.createElement('div');
  document.body.appendChild(container);
});

afterEach(() => {
  // cleanup on exiting
  unmountComponentAtNode(container);
  container.remove();
  container = null;
});

function test() {
  return true;
}

describe('FormContainer View', () => {
  it('renders FormContainer', () => {
    act(() => {
      render(
        <FormContainer
          state={{
            selectedTask: {
              id: 11,
              title: 'dicta aperiam aut ipsam amet',
              text:
                'inventore quia laudantium officia labore qui est qui distinctio ut laboriosam dolorem quaerat nemo placeat minus corporis ut illo id incidunt sint dolor commodi qui ipsa est est ab asperiores blanditiis voluptates eum in placeat quia possimus rem eaque facere cum facere minus assumenda quam dolor libero quos amet sapiente',
              categoryID: 1,
              isFirstDutyStation: false,
              isFirstTermAirman: true,
              isOfficer: false,
              verificationRequired: true,
              location: '2128 Carrie Coves',
              office: 'Accounts',
              pocName: 'Lurline Kreiger',
              pocPhoneNumber: '371-058-6598 x6370',
              pocEmail: 'Emmalee78@hotmail.com',
              createdAt: '2021-04-30T14:00:49.261Z',
              updatedAt: '2021-04-30T14:00:49.261Z',
            },
            showTaskForm: true,
            units: [
              {
                id: 1,
                name: "Ziemann, O'Kon and Schmitt",
                baseID: 1,
                createdAt: '2021-04-30T14:00:49.613Z',
                updatedAt: '2021-04-30T14:00:49.613Z',
              },
              {
                id: 2,
                name: 'Bayer - Pfannerstill',
                baseID: 1,
                createdAt: '2021-04-30T14:00:49.624Z',
                updatedAt: '2021-04-30T14:00:49.624Z',
              },
            ],
            categories: [
              {
                tasks: [
                  {
                    id: 11,
                    title: 'dicta aperiam aut ipsam amet',
                    text:
                      'inventore quia laudantium officia labore qui est qui distinctio ut laboriosam dolorem quaerat nemo placeat minus corporis ut illo id incidunt sint dolor commodi qui ipsa est est ab asperiores blanditiis voluptates eum in placeat quia possimus rem eaque facere cum facere minus assumenda quam dolor libero quos amet sapiente',
                    categoryID: 1,
                    isFirstDutyStation: false,
                    isFirstTermAirman: true,
                    isOfficer: false,
                    verificationRequired: true,
                    location: '2128 Carrie Coves',
                    office: 'Accounts',
                    pocName: 'Lurline Kreiger',
                    pocPhoneNumber: '371-058-6598 x6370',
                    pocEmail: 'Emmalee78@hotmail.com',
                    createdAt: '2021-04-30T14:00:49.261Z',
                    updatedAt: '2021-04-30T14:00:49.261Z',
                  },
                ],
                id: 1,
                title: 'Hansen Group',
                ownerID: 1,
                createdAt: '2021-04-30T14:00:48.885Z',
                updatedAt: '2021-04-30T14:00:48.885Z',
              },
              {
                tasks: [
                  {
                    id: 3,
                    title: 'itaque nihil nobis rerum accusantium',
                    text:
                      'aut non ea et eius dicta dolor minima error maiores mollitia rerum quis qui doloribus blanditiis rerum distinctio commodi aliquid quod vel soluta qui quam beatae voluptas magni et nulla cum reprehenderit dolor tempora vel repellendus voluptas adipisci alias esse qui delectus deserunt quasi blanditiis suscipit voluptates ut sequi iste',
                    categoryID: 7,
                    isFirstDutyStation: true,
                    isFirstTermAirman: false,
                    isOfficer: true,
                    verificationRequired: false,
                    location: '579 Faustino Streets',
                    office: 'Integration',
                    pocName: 'Antone Brekke',
                    pocPhoneNumber: '100.754.4864',
                    pocEmail: 'Cristopher.Ebert@gmail.com',
                    createdAt: '2021-04-30T14:00:49.115Z',
                    updatedAt: '2021-04-30T14:00:49.115Z',
                  },
                  {
                    id: 4,
                    title: 'repellendus dolorem iure tempore quidem',
                    text:
                      'doloribus enim voluptatem sit repudiandae quo quia consequatur voluptas voluptatibus eum corrupti doloremque sed dolorem molestiae doloribus amet quam animi a impedit beatae non temporibus est alias dolorum inventore expedita blanditiis fugiat sint quia aperiam aliquid quia sequi beatae non ut quae impedit laudantium deleniti ab est ullam amet et',
                    categoryID: 7,
                    isFirstDutyStation: true,
                    isFirstTermAirman: true,
                    isOfficer: true,
                    verificationRequired: false,
                    location: '93035 Feest Parkway',
                    office: 'Brand',
                    pocName: 'Josiane Schinner',
                    pocPhoneNumber: '922-636-2586 x42668',
                    pocEmail: 'Eugene37@yahoo.com',
                    createdAt: '2021-04-30T14:00:49.131Z',
                    updatedAt: '2021-04-30T14:00:49.131Z',
                  },
                  {
                    id: 7,
                    title: 'et id vitae omnis doloribus',
                    text:
                      'quasi aliquam eligendi accusamus molestiae amet enim dolorum voluptas est est maiores ex omnis sapiente tempore qui expedita provident odio nobis rerum voluptatem inventore hic quia dolorem debitis et saepe hic velit quia deleniti culpa sunt exercitationem optio doloremque a sit laborum aut laboriosam illum sit non omnis eligendi possimus',
                    categoryID: 7,
                    isFirstDutyStation: false,
                    isFirstTermAirman: false,
                    isOfficer: false,
                    verificationRequired: true,
                    location: '20191 Kuvalis Key',
                    office: 'Applications',
                    pocName: 'Gilberto Collier',
                    pocPhoneNumber: '234-076-0664 x2239',
                    pocEmail: 'Zachery.Moore5@gmail.com',
                    createdAt: '2021-04-30T14:00:49.188Z',
                    updatedAt: '2021-04-30T14:00:49.188Z',
                  },
                  {
                    id: 10,
                    title: 'aut est et consequatur omnis',
                    text:
                      'esse eaque incidunt delectus eveniet eius aspernatur voluptates asperiores in rerum officiis tempore nemo enim consequuntur aut molestiae autem officia dolor at magni qui dolor totam delectus aliquam mollitia fugiat qui eos ut omnis quo harum nisi rerum nihil et dolor accusamus ullam sunt explicabo porro velit aperiam architecto sed',
                    categoryID: 7,
                    isFirstDutyStation: false,
                    isFirstTermAirman: false,
                    isOfficer: true,
                    verificationRequired: true,
                    location: '103 Friesen Crossroad',
                    office: 'Accounts',
                    pocName: 'Ally Pacocha',
                    pocPhoneNumber: '1-563-751-4180 x2292',
                    pocEmail: 'Elsie.Torphy@yahoo.com',
                    createdAt: '2021-04-30T14:00:49.244Z',
                    updatedAt: '2021-04-30T14:00:49.244Z',
                  },
                  {
                    id: 22,
                    title: 'quae aut neque sequi rem',
                    text:
                      'natus atque et animi sit qui sed voluptatem laudantium ipsa culpa non suscipit error consequuntur voluptatem blanditiis omnis aut quis ut aperiam ea doloribus eos dolore quis qui nobis aut saepe neque perspiciatis eos vitae minima autem eveniet voluptas accusantium est tempore cum aliquid ut velit voluptatem repellat enim omnis',
                    categoryID: 7,
                    isFirstDutyStation: false,
                    isFirstTermAirman: true,
                    isOfficer: false,
                    verificationRequired: false,
                    location: '5875 Willis Inlet',
                    office: 'Brand',
                    pocName: 'Darius Crooks',
                    pocPhoneNumber: '219-034-1028 x95980',
                    pocEmail: 'Gertrude.Cormier@gmail.com',
                    createdAt: '2021-04-30T14:00:49.449Z',
                    updatedAt: '2021-04-30T14:00:49.449Z',
                  },
                  {
                    id: 25,
                    title: 'asperiores quam aliquam quae dolores',
                    text:
                      'aliquam aut sint autem necessitatibus voluptas nobis id ipsum debitis impedit ipsum ut rem voluptates quae aut molestiae iure quaerat sit sed facere dolorem est natus officiis quis sit minima at minima corrupti natus repellendus et dolor sapiente doloremque quibusdam suscipit explicabo voluptatem consequatur iusto doloremque quo quidem delectus sit',
                    categoryID: 7,
                    isFirstDutyStation: false,
                    isFirstTermAirman: false,
                    isOfficer: true,
                    verificationRequired: true,
                    location: '728 Lenore Crest',
                    office: 'Brand',
                    pocName: 'Marcia Emmerich',
                    pocPhoneNumber: '514-242-0184',
                    pocEmail: 'Alysson_Herman@yahoo.com',
                    createdAt: '2021-04-30T14:00:49.530Z',
                    updatedAt: '2021-04-30T14:00:49.530Z',
                  },
                ],
                id: 7,
                title: 'Wilkinson, Bernier and Franecki',
                ownerID: 2,
                createdAt: '2021-04-30T14:00:48.986Z',
                updatedAt: '2021-04-30T14:00:48.986Z',
              },
              {
                tasks: [
                  {
                    id: 1,
                    title: 'suscipit maxime a quia in',
                    text:
                      'fugiat voluptates sint sequi inventore et accusamus dolor debitis distinctio ipsa fuga nemo officia nemo minima architecto enim deserunt ex delectus ex magni repellat odit ipsa sunt hic ut nulla ut velit possimus velit neque itaque modi aut vero minima fugiat aliquam quod ex aperiam et unde sunt tempore vel',
                    categoryID: 5,
                    isFirstDutyStation: true,
                    isFirstTermAirman: false,
                    isOfficer: false,
                    verificationRequired: true,
                    location: '0746 Kali Forges',
                    office: 'Solutions',
                    pocName: 'Name Moore',
                    pocPhoneNumber: '586.069.8394',
                    pocEmail: 'Katherine.McLaughlin@gmail.com',
                    createdAt: '2021-04-30T14:00:49.076Z',
                    updatedAt: '2021-04-30T14:00:49.076Z',
                  },
                  {
                    id: 17,
                    title: 'consequatur debitis cupiditate magnam voluptatem',
                    text:
                      'quaerat non cumque cupiditate officiis sed autem atque vero quod et nulla asperiores dignissimos occaecati et nostrum expedita qui tempora veritatis dolor ut asperiores est incidunt modi et fugiat libero unde delectus veniam numquam labore ut iste qui quia veniam eum inventore velit magnam quis non rem blanditiis ab explicabo',
                    categoryID: 5,
                    isFirstDutyStation: true,
                    isFirstTermAirman: false,
                    isOfficer: false,
                    verificationRequired: false,
                    location: '00761 Turner Station',
                    office: 'Accounts',
                    pocName: 'Gladyce Cummings',
                    pocPhoneNumber: '(159) 507-2754',
                    pocEmail: 'Geraldine.Jakubowski49@gmail.com',
                    createdAt: '2021-04-30T14:00:49.354Z',
                    updatedAt: '2021-04-30T14:00:49.354Z',
                  },
                  {
                    id: 23,
                    title: 'et dolor non illum ut',
                    text:
                      'cum error omnis earum deleniti sit aut officiis laborum ipsam voluptatem laudantium illum non vel voluptatem in eum enim iste illum reiciendis enim porro voluptate consequatur similique error et tenetur repellat sunt asperiores autem optio ea nostrum blanditiis culpa blanditiis dolor qui vel et dolor assumenda consequuntur et earum quasi',
                    categoryID: 5,
                    isFirstDutyStation: false,
                    isFirstTermAirman: false,
                    isOfficer: false,
                    verificationRequired: true,
                    location: '98881 Fae Mountain',
                    office: 'Marketing',
                    pocName: 'Forest Mayert',
                    pocPhoneNumber: '(345) 838-8304',
                    pocEmail: 'Dominique.Ankunding37@yahoo.com',
                    createdAt: '2021-04-30T14:00:49.485Z',
                    updatedAt: '2021-04-30T14:00:49.485Z',
                  },
                  {
                    id: 28,
                    title: 'sequi consequatur sunt nobis repellat',
                    text:
                      'saepe qui dolore vitae vel illo aut neque soluta nostrum sunt quia perspiciatis adipisci sed tenetur cupiditate quidem repudiandae consequatur voluptatum in vero dignissimos animi qui odio exercitationem consequuntur in doloribus consequatur aliquam quia placeat aperiam dolores omnis placeat voluptatem quae iure facere consequatur facere asperiores corrupti et eligendi omnis',
                    categoryID: 5,
                    isFirstDutyStation: false,
                    isFirstTermAirman: true,
                    isOfficer: true,
                    verificationRequired: false,
                    location: '88283 Katheryn Rapid',
                    office: 'Accountability',
                    pocName: 'Candido Kuvalis',
                    pocPhoneNumber: '(404) 884-4741',
                    pocEmail: 'Maurice9@hotmail.com',
                    createdAt: '2021-04-30T14:00:49.575Z',
                    updatedAt: '2021-04-30T14:00:49.575Z',
                  },
                ],
                id: 5,
                title: "O'Hara, Abbott and Kshlerin",
                ownerID: 7,
                createdAt: '2021-04-30T14:00:48.959Z',
                updatedAt: '2021-04-30T14:00:48.959Z',
              },
              {
                tasks: [
                  {
                    id: 2,
                    title: 'dolores optio ex ad commodi',
                    text:
                      'quo temporibus accusantium aut molestiae qui a et soluta et mollitia unde cumque dicta aliquam deleniti corporis aliquid nemo odit voluptate quod odio ipsa expedita quos nihil quos dolorem vel minus minima similique sit nihil necessitatibus doloribus quae id atque at et dolorum sed quis eum porro sapiente beatae provident',
                    categoryID: 9,
                    isFirstDutyStation: true,
                    isFirstTermAirman: true,
                    isOfficer: false,
                    verificationRequired: false,
                    location: '46587 Aubree Village',
                    office: 'Applications',
                    pocName: 'Cydney Wisoky',
                    pocPhoneNumber: '626-017-7809 x8029',
                    pocEmail: 'Elvie9@gmail.com',
                    createdAt: '2021-04-30T14:00:49.094Z',
                    updatedAt: '2021-04-30T14:00:49.094Z',
                  },
                  {
                    id: 8,
                    title: 'eos placeat non dolor consectetur',
                    text:
                      'voluptate ab corporis voluptate debitis consequuntur ullam repudiandae dolorem totam et inventore dignissimos consequuntur amet doloremque iure quos quasi delectus sapiente minus assumenda vel consequatur culpa magni omnis aut maxime odit labore praesentium ipsa quidem iure saepe quis qui quae ratione fugiat qui culpa aperiam provident quo corporis delectus dolorum',
                    categoryID: 9,
                    isFirstDutyStation: false,
                    isFirstTermAirman: true,
                    isOfficer: false,
                    verificationRequired: true,
                    location: '3931 Trycia Roads',
                    office: 'Branding',
                    pocName: "Diana D'Amore",
                    pocPhoneNumber: '(856) 170-7266 x062',
                    pocEmail: 'Mark.Gerlach56@gmail.com',
                    createdAt: '2021-04-30T14:00:49.214Z',
                    updatedAt: '2021-04-30T14:00:49.214Z',
                  },
                  {
                    id: 13,
                    title: 'a id veritatis delectus aut',
                    text:
                      'cupiditate ratione omnis cupiditate aut deleniti quaerat aliquid ut tenetur voluptatem non asperiores neque sed aspernatur facere tempora quo eius ex vitae aut labore ratione eius sint earum tempora rerum sed sed eos dolores tempore et molestiae architecto iste accusamus est atque minima qui et dolor a omnis sunt ut',
                    categoryID: 9,
                    isFirstDutyStation: true,
                    isFirstTermAirman: false,
                    isOfficer: true,
                    verificationRequired: false,
                    location: '330 Nitzsche Inlet',
                    office: 'Usability',
                    pocName: 'Neal Abernathy',
                    pocPhoneNumber: '1-286-251-1677',
                    pocEmail: 'Green_Abernathy@gmail.com',
                    createdAt: '2021-04-30T14:00:49.289Z',
                    updatedAt: '2021-04-30T14:00:49.289Z',
                  },
                  {
                    id: 29,
                    title: 'rerum est qui aperiam dolorem',
                    text:
                      'molestiae saepe non laboriosam distinctio ratione pariatur dignissimos quasi dolor tempora aliquid est consequuntur asperiores cumque ad officia odio doloribus optio dolorem et occaecati sint soluta soluta dolore labore facilis ea aut voluptas saepe aperiam qui repellendus ut officiis id aut adipisci cumque harum ad aliquid odit excepturi voluptates neque',
                    categoryID: 9,
                    isFirstDutyStation: true,
                    isFirstTermAirman: true,
                    isOfficer: true,
                    verificationRequired: false,
                    location: '9937 Brakus Mall',
                    office: 'Implementation',
                    pocName: 'Oleta Beahan',
                    pocPhoneNumber: '1-441-366-9277 x007',
                    pocEmail: 'Beau_Eichmann@gmail.com',
                    createdAt: '2021-04-30T14:00:49.586Z',
                    updatedAt: '2021-04-30T14:00:49.586Z',
                  },
                ],
                id: 9,
                title: 'Ernser - VonRueden',
                ownerID: 7,
                createdAt: '2021-04-30T14:00:49.020Z',
                updatedAt: '2021-04-30T14:00:49.020Z',
              },
              {
                tasks: [
                  {
                    id: 6,
                    title: 'perspiciatis debitis rerum neque sint',
                    text:
                      'fugit quibusdam et iusto temporibus rerum asperiores optio corrupti vel voluptatem perspiciatis deleniti ut excepturi veritatis excepturi autem earum et eos excepturi impedit sit voluptatibus accusamus exercitationem voluptatibus et quia odio ipsa perferendis aliquid sit libero necessitatibus fugit enim ut facere beatae aut debitis necessitatibus voluptates iste doloribus eligendi dolores',
                    categoryID: 8,
                    isFirstDutyStation: true,
                    isFirstTermAirman: false,
                    isOfficer: false,
                    verificationRequired: true,
                    location: '308 Wilkinson Mission',
                    office: 'Intranet',
                    pocName: 'Edmund Simonis',
                    pocPhoneNumber: '1-461-058-2685',
                    pocEmail: 'Emilia51@hotmail.com',
                    createdAt: '2021-04-30T14:00:49.172Z',
                    updatedAt: '2021-04-30T14:00:49.172Z',
                  },
                  {
                    id: 30,
                    title: 'facilis quis quaerat excepturi magnam',
                    text:
                      'pariatur qui eaque dolorum repellendus doloremque exercitationem quas et autem odit ipsa voluptas dolores quis velit in quisquam aliquid facere itaque voluptatem dolorum itaque nam natus in nemo dolorem nisi error sequi modi magnam sed nobis magnam est est quam sed et provident deleniti omnis velit inventore consequatur autem qui',
                    categoryID: 8,
                    isFirstDutyStation: false,
                    isFirstTermAirman: true,
                    isOfficer: true,
                    verificationRequired: true,
                    location: '87093 Bernardo Rest',
                    office: 'Applications',
                    pocName: 'Clinton Jerde',
                    pocPhoneNumber: '190-472-5013 x38343',
                    pocEmail: 'Nona.Lehner3@yahoo.com',
                    createdAt: '2021-04-30T14:00:49.598Z',
                    updatedAt: '2021-04-30T14:00:49.598Z',
                  },
                ],
                id: 8,
                title: 'Gleason Inc',
                ownerID: 8,
                createdAt: '2021-04-30T14:00:49.003Z',
                updatedAt: '2021-04-30T14:00:49.003Z',
              },
              {
                tasks: [],
                id: 10,
                title: 'Turcotte - Kovacek',
                ownerID: 8,
                createdAt: '2021-04-30T14:00:49.052Z',
                updatedAt: '2021-04-30T14:00:49.052Z',
              },
              {
                tasks: [
                  {
                    id: 12,
                    title: 'dolores consequuntur et vero molestiae',
                    text:
                      'non mollitia iste omnis omnis nostrum eius est eveniet dolore ut voluptates vel aperiam rerum eum molestiae dolore eius id et ea quibusdam dicta accusamus ullam nulla eligendi ut sed non alias adipisci ex exercitationem repudiandae minus qui velit porro quae nostrum rerum illo ex asperiores voluptatum a repellat aspernatur',
                    categoryID: 4,
                    isFirstDutyStation: false,
                    isFirstTermAirman: true,
                    isOfficer: false,
                    verificationRequired: false,
                    location: '385 Hoppe Vista',
                    office: 'Research',
                    pocName: 'Bridgette Kshlerin',
                    pocPhoneNumber: '(162) 495-0418',
                    pocEmail: 'Alia78@gmail.com',
                    createdAt: '2021-04-30T14:00:49.277Z',
                    updatedAt: '2021-04-30T14:00:49.277Z',
                  },
                  {
                    id: 21,
                    title: 'delectus quasi neque necessitatibus dolor',
                    text:
                      'et expedita dicta repellendus exercitationem sint facere numquam totam enim optio culpa culpa et temporibus odit neque suscipit sed ipsum et sunt exercitationem provident sint eum dicta sequi delectus ut quo fugit aut quis ut et sapiente assumenda sed nobis ut temporibus voluptatum accusantium omnis alias asperiores ex rerum incidunt',
                    categoryID: 4,
                    isFirstDutyStation: true,
                    isFirstTermAirman: false,
                    isOfficer: true,
                    verificationRequired: false,
                    location: '482 Cooper Greens',
                    office: 'Intranet',
                    pocName: 'Litzy Smith',
                    pocPhoneNumber: '1-412-529-2261 x57069',
                    pocEmail: 'Amina_Walker@hotmail.com',
                    createdAt: '2021-04-30T14:00:49.422Z',
                    updatedAt: '2021-04-30T14:00:49.422Z',
                  },
                  {
                    id: 27,
                    title: 'cupiditate laboriosam est labore animi',
                    text:
                      'expedita velit asperiores aliquam in natus dicta voluptas voluptatem similique excepturi et cum consequatur delectus dolore rerum unde cum enim ipsa architecto qui eligendi quia magnam omnis hic doloremque distinctio eos esse dolor numquam nostrum inventore veritatis ad soluta aspernatur culpa nostrum dolorem deserunt harum saepe asperiores voluptatem ipsa laboriosam',
                    categoryID: 4,
                    isFirstDutyStation: true,
                    isFirstTermAirman: true,
                    isOfficer: true,
                    verificationRequired: true,
                    location: '32082 Benny Pines',
                    office: 'Tactics',
                    pocName: 'Jed Keeling',
                    pocPhoneNumber: '(094) 406-8637 x06863',
                    pocEmail: 'Kayla_Moen@hotmail.com',
                    createdAt: '2021-04-30T14:00:49.562Z',
                    updatedAt: '2021-04-30T14:00:49.562Z',
                  },
                ],
                id: 4,
                title: 'Hauck, Reichel and Bogan',
                ownerID: 9,
                createdAt: '2021-04-30T14:00:48.942Z',
                updatedAt: '2021-04-30T14:00:48.942Z',
              },
              {
                tasks: [
                  {
                    id: 5,
                    title: 'asperiores reprehenderit laboriosam aliquid dolore',
                    text:
                      'qui labore deserunt commodi amet amet odio soluta eius nam beatae veritatis fuga fugit quia suscipit mollitia rem ut hic in autem pariatur ratione architecto voluptates minima dolor sint consequatur nihil fugiat dolorem ipsam ipsum quia aut aut voluptatem et deleniti est consectetur quasi consequatur ad eum occaecati dolores labore',
                    categoryID: 3,
                    isFirstDutyStation: true,
                    isFirstTermAirman: false,
                    isOfficer: true,
                    verificationRequired: false,
                    location: '9601 Ida Crossing',
                    office: 'Marketing',
                    pocName: 'Heloise Pouros',
                    pocPhoneNumber: '012.033.0272',
                    pocEmail: 'Kody56@gmail.com',
                    createdAt: '2021-04-30T14:00:49.153Z',
                    updatedAt: '2021-04-30T14:00:49.153Z',
                  },
                  {
                    id: 24,
                    title: 'recusandae et in laboriosam praesentium',
                    text:
                      'dolorem dolores ipsum eius adipisci quos molestiae laudantium et excepturi et mollitia aut et eaque est a commodi quod hic vel ea dolorum id perferendis voluptatem ab totam in qui quo dicta quis ut asperiores consequatur aut error occaecati aut aspernatur et vel aut vel rem delectus eos aliquam blanditiis',
                    categoryID: 3,
                    isFirstDutyStation: true,
                    isFirstTermAirman: true,
                    isOfficer: true,
                    verificationRequired: true,
                    location: '06613 Tromp Parkways',
                    office: 'Response',
                    pocName: "Loraine O'Hara",
                    pocPhoneNumber: '022-493-0293 x58144',
                    pocEmail: 'Blanche_Abshire@gmail.com',
                    createdAt: '2021-04-30T14:00:49.503Z',
                    updatedAt: '2021-04-30T14:00:49.503Z',
                  },
                ],
                id: 3,
                title: "Marquardt, Durgan and O'Hara",
                ownerID: 10,
                createdAt: '2021-04-30T14:00:48.924Z',
                updatedAt: '2021-04-30T14:00:48.924Z',
              },
              {
                tasks: [
                  {
                    id: 19,
                    title: 'ut rerum doloremque soluta qui',
                    text:
                      'qui placeat sunt aspernatur officiis molestiae id laudantium libero et sed voluptatem et illum reprehenderit est nobis sit laborum facere debitis fuga qui quibusdam sit neque exercitationem necessitatibus rem pariatur neque repellendus harum dolore eos libero rerum saepe voluptas tempore aliquam sit quae doloribus a minima facilis saepe tenetur quia',
                    categoryID: 6,
                    isFirstDutyStation: false,
                    isFirstTermAirman: true,
                    isOfficer: true,
                    verificationRequired: false,
                    location: '2914 Creola Rue',
                    office: 'Optimization',
                    pocName: 'Pete Halvorson',
                    pocPhoneNumber: '(577) 738-0979 x65921',
                    pocEmail: 'Melisa_Botsford64@gmail.com',
                    createdAt: '2021-04-30T14:00:49.392Z',
                    updatedAt: '2021-04-30T14:00:49.392Z',
                  },
                ],
                id: 6,
                title: 'Hoeger LLC',
                ownerID: 10,
                createdAt: '2021-04-30T14:00:48.973Z',
                updatedAt: '2021-04-30T14:00:48.973Z',
              },
            ],
            status: 'idle',
          }}
          actions={{ id: 1 }}
        />,
        container
      );
    });
    expect(
      screen.getByRole('heading', { name: /Add a Task/i })
    ).toBeInTheDocument();
  });

  it('close button works', () => {
    const fn = jest.fn();
    render(
      <FormContainer
        state={{
          selectedTask: {
            id: 11,
            title: 'dicta aperiam aut ipsam amet',
            text:
              'inventore quia laudantium officia labore qui est qui distinctio ut laboriosam dolorem quaerat nemo placeat minus corporis ut illo id incidunt sint dolor commodi qui ipsa est est ab asperiores blanditiis voluptates eum in placeat quia possimus rem eaque facere cum facere minus assumenda quam dolor libero quos amet sapiente',
            categoryID: 1,
            isFirstDutyStation: false,
            isFirstTermAirman: true,
            isOfficer: false,
            verificationRequired: true,
            location: '2128 Carrie Coves',
            office: 'Accounts',
            pocName: 'Lurline Kreiger',
            pocPhoneNumber: '371-058-6598 x6370',
            pocEmail: 'Emmalee78@hotmail.com',
            createdAt: '2021-04-30T14:00:49.261Z',
            updatedAt: '2021-04-30T14:00:49.261Z',
          },
          showTaskForm: true,
          units: [
            {
              id: 1,
              name: "Ziemann, O'Kon and Schmitt",
              baseID: 1,
              createdAt: '2021-04-30T14:00:49.613Z',
              updatedAt: '2021-04-30T14:00:49.613Z',
            },
            {
              id: 2,
              name: 'Bayer - Pfannerstill',
              baseID: 1,
              createdAt: '2021-04-30T14:00:49.624Z',
              updatedAt: '2021-04-30T14:00:49.624Z',
            },
          ],
          categories: [
            {
              tasks: [
                {
                  id: 11,
                  title: 'dicta aperiam aut ipsam amet',
                  text:
                    'inventore quia laudantium officia labore qui est qui distinctio ut laboriosam dolorem quaerat nemo placeat minus corporis ut illo id incidunt sint dolor commodi qui ipsa est est ab asperiores blanditiis voluptates eum in placeat quia possimus rem eaque facere cum facere minus assumenda quam dolor libero quos amet sapiente',
                  categoryID: 1,
                  isFirstDutyStation: false,
                  isFirstTermAirman: true,
                  isOfficer: false,
                  verificationRequired: true,
                  location: '2128 Carrie Coves',
                  office: 'Accounts',
                  pocName: 'Lurline Kreiger',
                  pocPhoneNumber: '371-058-6598 x6370',
                  pocEmail: 'Emmalee78@hotmail.com',
                  createdAt: '2021-04-30T14:00:49.261Z',
                  updatedAt: '2021-04-30T14:00:49.261Z',
                },
              ],
              id: 1,
              title: 'Hansen Group',
              ownerID: 1,
              createdAt: '2021-04-30T14:00:48.885Z',
              updatedAt: '2021-04-30T14:00:48.885Z',
            },
            {
              tasks: [
                {
                  id: 3,
                  title: 'itaque nihil nobis rerum accusantium',
                  text:
                    'aut non ea et eius dicta dolor minima error maiores mollitia rerum quis qui doloribus blanditiis rerum distinctio commodi aliquid quod vel soluta qui quam beatae voluptas magni et nulla cum reprehenderit dolor tempora vel repellendus voluptas adipisci alias esse qui delectus deserunt quasi blanditiis suscipit voluptates ut sequi iste',
                  categoryID: 7,
                  isFirstDutyStation: true,
                  isFirstTermAirman: false,
                  isOfficer: true,
                  verificationRequired: false,
                  location: '579 Faustino Streets',
                  office: 'Integration',
                  pocName: 'Antone Brekke',
                  pocPhoneNumber: '100.754.4864',
                  pocEmail: 'Cristopher.Ebert@gmail.com',
                  createdAt: '2021-04-30T14:00:49.115Z',
                  updatedAt: '2021-04-30T14:00:49.115Z',
                },
                {
                  id: 4,
                  title: 'repellendus dolorem iure tempore quidem',
                  text:
                    'doloribus enim voluptatem sit repudiandae quo quia consequatur voluptas voluptatibus eum corrupti doloremque sed dolorem molestiae doloribus amet quam animi a impedit beatae non temporibus est alias dolorum inventore expedita blanditiis fugiat sint quia aperiam aliquid quia sequi beatae non ut quae impedit laudantium deleniti ab est ullam amet et',
                  categoryID: 7,
                  isFirstDutyStation: true,
                  isFirstTermAirman: true,
                  isOfficer: true,
                  verificationRequired: false,
                  location: '93035 Feest Parkway',
                  office: 'Brand',
                  pocName: 'Josiane Schinner',
                  pocPhoneNumber: '922-636-2586 x42668',
                  pocEmail: 'Eugene37@yahoo.com',
                  createdAt: '2021-04-30T14:00:49.131Z',
                  updatedAt: '2021-04-30T14:00:49.131Z',
                },
                {
                  id: 7,
                  title: 'et id vitae omnis doloribus',
                  text:
                    'quasi aliquam eligendi accusamus molestiae amet enim dolorum voluptas est est maiores ex omnis sapiente tempore qui expedita provident odio nobis rerum voluptatem inventore hic quia dolorem debitis et saepe hic velit quia deleniti culpa sunt exercitationem optio doloremque a sit laborum aut laboriosam illum sit non omnis eligendi possimus',
                  categoryID: 7,
                  isFirstDutyStation: false,
                  isFirstTermAirman: false,
                  isOfficer: false,
                  verificationRequired: true,
                  location: '20191 Kuvalis Key',
                  office: 'Applications',
                  pocName: 'Gilberto Collier',
                  pocPhoneNumber: '234-076-0664 x2239',
                  pocEmail: 'Zachery.Moore5@gmail.com',
                  createdAt: '2021-04-30T14:00:49.188Z',
                  updatedAt: '2021-04-30T14:00:49.188Z',
                },
                {
                  id: 10,
                  title: 'aut est et consequatur omnis',
                  text:
                    'esse eaque incidunt delectus eveniet eius aspernatur voluptates asperiores in rerum officiis tempore nemo enim consequuntur aut molestiae autem officia dolor at magni qui dolor totam delectus aliquam mollitia fugiat qui eos ut omnis quo harum nisi rerum nihil et dolor accusamus ullam sunt explicabo porro velit aperiam architecto sed',
                  categoryID: 7,
                  isFirstDutyStation: false,
                  isFirstTermAirman: false,
                  isOfficer: true,
                  verificationRequired: true,
                  location: '103 Friesen Crossroad',
                  office: 'Accounts',
                  pocName: 'Ally Pacocha',
                  pocPhoneNumber: '1-563-751-4180 x2292',
                  pocEmail: 'Elsie.Torphy@yahoo.com',
                  createdAt: '2021-04-30T14:00:49.244Z',
                  updatedAt: '2021-04-30T14:00:49.244Z',
                },
                {
                  id: 22,
                  title: 'quae aut neque sequi rem',
                  text:
                    'natus atque et animi sit qui sed voluptatem laudantium ipsa culpa non suscipit error consequuntur voluptatem blanditiis omnis aut quis ut aperiam ea doloribus eos dolore quis qui nobis aut saepe neque perspiciatis eos vitae minima autem eveniet voluptas accusantium est tempore cum aliquid ut velit voluptatem repellat enim omnis',
                  categoryID: 7,
                  isFirstDutyStation: false,
                  isFirstTermAirman: true,
                  isOfficer: false,
                  verificationRequired: false,
                  location: '5875 Willis Inlet',
                  office: 'Brand',
                  pocName: 'Darius Crooks',
                  pocPhoneNumber: '219-034-1028 x95980',
                  pocEmail: 'Gertrude.Cormier@gmail.com',
                  createdAt: '2021-04-30T14:00:49.449Z',
                  updatedAt: '2021-04-30T14:00:49.449Z',
                },
                {
                  id: 25,
                  title: 'asperiores quam aliquam quae dolores',
                  text:
                    'aliquam aut sint autem necessitatibus voluptas nobis id ipsum debitis impedit ipsum ut rem voluptates quae aut molestiae iure quaerat sit sed facere dolorem est natus officiis quis sit minima at minima corrupti natus repellendus et dolor sapiente doloremque quibusdam suscipit explicabo voluptatem consequatur iusto doloremque quo quidem delectus sit',
                  categoryID: 7,
                  isFirstDutyStation: false,
                  isFirstTermAirman: false,
                  isOfficer: true,
                  verificationRequired: true,
                  location: '728 Lenore Crest',
                  office: 'Brand',
                  pocName: 'Marcia Emmerich',
                  pocPhoneNumber: '514-242-0184',
                  pocEmail: 'Alysson_Herman@yahoo.com',
                  createdAt: '2021-04-30T14:00:49.530Z',
                  updatedAt: '2021-04-30T14:00:49.530Z',
                },
              ],
              id: 7,
              title: 'Wilkinson, Bernier and Franecki',
              ownerID: 2,
              createdAt: '2021-04-30T14:00:48.986Z',
              updatedAt: '2021-04-30T14:00:48.986Z',
            },
            {
              tasks: [
                {
                  id: 1,
                  title: 'suscipit maxime a quia in',
                  text:
                    'fugiat voluptates sint sequi inventore et accusamus dolor debitis distinctio ipsa fuga nemo officia nemo minima architecto enim deserunt ex delectus ex magni repellat odit ipsa sunt hic ut nulla ut velit possimus velit neque itaque modi aut vero minima fugiat aliquam quod ex aperiam et unde sunt tempore vel',
                  categoryID: 5,
                  isFirstDutyStation: true,
                  isFirstTermAirman: false,
                  isOfficer: false,
                  verificationRequired: true,
                  location: '0746 Kali Forges',
                  office: 'Solutions',
                  pocName: 'Name Moore',
                  pocPhoneNumber: '586.069.8394',
                  pocEmail: 'Katherine.McLaughlin@gmail.com',
                  createdAt: '2021-04-30T14:00:49.076Z',
                  updatedAt: '2021-04-30T14:00:49.076Z',
                },
                {
                  id: 17,
                  title: 'consequatur debitis cupiditate magnam voluptatem',
                  text:
                    'quaerat non cumque cupiditate officiis sed autem atque vero quod et nulla asperiores dignissimos occaecati et nostrum expedita qui tempora veritatis dolor ut asperiores est incidunt modi et fugiat libero unde delectus veniam numquam labore ut iste qui quia veniam eum inventore velit magnam quis non rem blanditiis ab explicabo',
                  categoryID: 5,
                  isFirstDutyStation: true,
                  isFirstTermAirman: false,
                  isOfficer: false,
                  verificationRequired: false,
                  location: '00761 Turner Station',
                  office: 'Accounts',
                  pocName: 'Gladyce Cummings',
                  pocPhoneNumber: '(159) 507-2754',
                  pocEmail: 'Geraldine.Jakubowski49@gmail.com',
                  createdAt: '2021-04-30T14:00:49.354Z',
                  updatedAt: '2021-04-30T14:00:49.354Z',
                },
                {
                  id: 23,
                  title: 'et dolor non illum ut',
                  text:
                    'cum error omnis earum deleniti sit aut officiis laborum ipsam voluptatem laudantium illum non vel voluptatem in eum enim iste illum reiciendis enim porro voluptate consequatur similique error et tenetur repellat sunt asperiores autem optio ea nostrum blanditiis culpa blanditiis dolor qui vel et dolor assumenda consequuntur et earum quasi',
                  categoryID: 5,
                  isFirstDutyStation: false,
                  isFirstTermAirman: false,
                  isOfficer: false,
                  verificationRequired: true,
                  location: '98881 Fae Mountain',
                  office: 'Marketing',
                  pocName: 'Forest Mayert',
                  pocPhoneNumber: '(345) 838-8304',
                  pocEmail: 'Dominique.Ankunding37@yahoo.com',
                  createdAt: '2021-04-30T14:00:49.485Z',
                  updatedAt: '2021-04-30T14:00:49.485Z',
                },
                {
                  id: 28,
                  title: 'sequi consequatur sunt nobis repellat',
                  text:
                    'saepe qui dolore vitae vel illo aut neque soluta nostrum sunt quia perspiciatis adipisci sed tenetur cupiditate quidem repudiandae consequatur voluptatum in vero dignissimos animi qui odio exercitationem consequuntur in doloribus consequatur aliquam quia placeat aperiam dolores omnis placeat voluptatem quae iure facere consequatur facere asperiores corrupti et eligendi omnis',
                  categoryID: 5,
                  isFirstDutyStation: false,
                  isFirstTermAirman: true,
                  isOfficer: true,
                  verificationRequired: false,
                  location: '88283 Katheryn Rapid',
                  office: 'Accountability',
                  pocName: 'Candido Kuvalis',
                  pocPhoneNumber: '(404) 884-4741',
                  pocEmail: 'Maurice9@hotmail.com',
                  createdAt: '2021-04-30T14:00:49.575Z',
                  updatedAt: '2021-04-30T14:00:49.575Z',
                },
              ],
              id: 5,
              title: "O'Hara, Abbott and Kshlerin",
              ownerID: 7,
              createdAt: '2021-04-30T14:00:48.959Z',
              updatedAt: '2021-04-30T14:00:48.959Z',
            },
            {
              tasks: [
                {
                  id: 2,
                  title: 'dolores optio ex ad commodi',
                  text:
                    'quo temporibus accusantium aut molestiae qui a et soluta et mollitia unde cumque dicta aliquam deleniti corporis aliquid nemo odit voluptate quod odio ipsa expedita quos nihil quos dolorem vel minus minima similique sit nihil necessitatibus doloribus quae id atque at et dolorum sed quis eum porro sapiente beatae provident',
                  categoryID: 9,
                  isFirstDutyStation: true,
                  isFirstTermAirman: true,
                  isOfficer: false,
                  verificationRequired: false,
                  location: '46587 Aubree Village',
                  office: 'Applications',
                  pocName: 'Cydney Wisoky',
                  pocPhoneNumber: '626-017-7809 x8029',
                  pocEmail: 'Elvie9@gmail.com',
                  createdAt: '2021-04-30T14:00:49.094Z',
                  updatedAt: '2021-04-30T14:00:49.094Z',
                },
                {
                  id: 8,
                  title: 'eos placeat non dolor consectetur',
                  text:
                    'voluptate ab corporis voluptate debitis consequuntur ullam repudiandae dolorem totam et inventore dignissimos consequuntur amet doloremque iure quos quasi delectus sapiente minus assumenda vel consequatur culpa magni omnis aut maxime odit labore praesentium ipsa quidem iure saepe quis qui quae ratione fugiat qui culpa aperiam provident quo corporis delectus dolorum',
                  categoryID: 9,
                  isFirstDutyStation: false,
                  isFirstTermAirman: true,
                  isOfficer: false,
                  verificationRequired: true,
                  location: '3931 Trycia Roads',
                  office: 'Branding',
                  pocName: "Diana D'Amore",
                  pocPhoneNumber: '(856) 170-7266 x062',
                  pocEmail: 'Mark.Gerlach56@gmail.com',
                  createdAt: '2021-04-30T14:00:49.214Z',
                  updatedAt: '2021-04-30T14:00:49.214Z',
                },
                {
                  id: 13,
                  title: 'a id veritatis delectus aut',
                  text:
                    'cupiditate ratione omnis cupiditate aut deleniti quaerat aliquid ut tenetur voluptatem non asperiores neque sed aspernatur facere tempora quo eius ex vitae aut labore ratione eius sint earum tempora rerum sed sed eos dolores tempore et molestiae architecto iste accusamus est atque minima qui et dolor a omnis sunt ut',
                  categoryID: 9,
                  isFirstDutyStation: true,
                  isFirstTermAirman: false,
                  isOfficer: true,
                  verificationRequired: false,
                  location: '330 Nitzsche Inlet',
                  office: 'Usability',
                  pocName: 'Neal Abernathy',
                  pocPhoneNumber: '1-286-251-1677',
                  pocEmail: 'Green_Abernathy@gmail.com',
                  createdAt: '2021-04-30T14:00:49.289Z',
                  updatedAt: '2021-04-30T14:00:49.289Z',
                },
                {
                  id: 29,
                  title: 'rerum est qui aperiam dolorem',
                  text:
                    'molestiae saepe non laboriosam distinctio ratione pariatur dignissimos quasi dolor tempora aliquid est consequuntur asperiores cumque ad officia odio doloribus optio dolorem et occaecati sint soluta soluta dolore labore facilis ea aut voluptas saepe aperiam qui repellendus ut officiis id aut adipisci cumque harum ad aliquid odit excepturi voluptates neque',
                  categoryID: 9,
                  isFirstDutyStation: true,
                  isFirstTermAirman: true,
                  isOfficer: true,
                  verificationRequired: false,
                  location: '9937 Brakus Mall',
                  office: 'Implementation',
                  pocName: 'Oleta Beahan',
                  pocPhoneNumber: '1-441-366-9277 x007',
                  pocEmail: 'Beau_Eichmann@gmail.com',
                  createdAt: '2021-04-30T14:00:49.586Z',
                  updatedAt: '2021-04-30T14:00:49.586Z',
                },
              ],
              id: 9,
              title: 'Ernser - VonRueden',
              ownerID: 7,
              createdAt: '2021-04-30T14:00:49.020Z',
              updatedAt: '2021-04-30T14:00:49.020Z',
            },
            {
              tasks: [
                {
                  id: 6,
                  title: 'perspiciatis debitis rerum neque sint',
                  text:
                    'fugit quibusdam et iusto temporibus rerum asperiores optio corrupti vel voluptatem perspiciatis deleniti ut excepturi veritatis excepturi autem earum et eos excepturi impedit sit voluptatibus accusamus exercitationem voluptatibus et quia odio ipsa perferendis aliquid sit libero necessitatibus fugit enim ut facere beatae aut debitis necessitatibus voluptates iste doloribus eligendi dolores',
                  categoryID: 8,
                  isFirstDutyStation: true,
                  isFirstTermAirman: false,
                  isOfficer: false,
                  verificationRequired: true,
                  location: '308 Wilkinson Mission',
                  office: 'Intranet',
                  pocName: 'Edmund Simonis',
                  pocPhoneNumber: '1-461-058-2685',
                  pocEmail: 'Emilia51@hotmail.com',
                  createdAt: '2021-04-30T14:00:49.172Z',
                  updatedAt: '2021-04-30T14:00:49.172Z',
                },
                {
                  id: 30,
                  title: 'facilis quis quaerat excepturi magnam',
                  text:
                    'pariatur qui eaque dolorum repellendus doloremque exercitationem quas et autem odit ipsa voluptas dolores quis velit in quisquam aliquid facere itaque voluptatem dolorum itaque nam natus in nemo dolorem nisi error sequi modi magnam sed nobis magnam est est quam sed et provident deleniti omnis velit inventore consequatur autem qui',
                  categoryID: 8,
                  isFirstDutyStation: false,
                  isFirstTermAirman: true,
                  isOfficer: true,
                  verificationRequired: true,
                  location: '87093 Bernardo Rest',
                  office: 'Applications',
                  pocName: 'Clinton Jerde',
                  pocPhoneNumber: '190-472-5013 x38343',
                  pocEmail: 'Nona.Lehner3@yahoo.com',
                  createdAt: '2021-04-30T14:00:49.598Z',
                  updatedAt: '2021-04-30T14:00:49.598Z',
                },
              ],
              id: 8,
              title: 'Gleason Inc',
              ownerID: 8,
              createdAt: '2021-04-30T14:00:49.003Z',
              updatedAt: '2021-04-30T14:00:49.003Z',
            },
            {
              tasks: [],
              id: 10,
              title: 'Turcotte - Kovacek',
              ownerID: 8,
              createdAt: '2021-04-30T14:00:49.052Z',
              updatedAt: '2021-04-30T14:00:49.052Z',
            },
            {
              tasks: [
                {
                  id: 12,
                  title: 'dolores consequuntur et vero molestiae',
                  text:
                    'non mollitia iste omnis omnis nostrum eius est eveniet dolore ut voluptates vel aperiam rerum eum molestiae dolore eius id et ea quibusdam dicta accusamus ullam nulla eligendi ut sed non alias adipisci ex exercitationem repudiandae minus qui velit porro quae nostrum rerum illo ex asperiores voluptatum a repellat aspernatur',
                  categoryID: 4,
                  isFirstDutyStation: false,
                  isFirstTermAirman: true,
                  isOfficer: false,
                  verificationRequired: false,
                  location: '385 Hoppe Vista',
                  office: 'Research',
                  pocName: 'Bridgette Kshlerin',
                  pocPhoneNumber: '(162) 495-0418',
                  pocEmail: 'Alia78@gmail.com',
                  createdAt: '2021-04-30T14:00:49.277Z',
                  updatedAt: '2021-04-30T14:00:49.277Z',
                },
                {
                  id: 21,
                  title: 'delectus quasi neque necessitatibus dolor',
                  text:
                    'et expedita dicta repellendus exercitationem sint facere numquam totam enim optio culpa culpa et temporibus odit neque suscipit sed ipsum et sunt exercitationem provident sint eum dicta sequi delectus ut quo fugit aut quis ut et sapiente assumenda sed nobis ut temporibus voluptatum accusantium omnis alias asperiores ex rerum incidunt',
                  categoryID: 4,
                  isFirstDutyStation: true,
                  isFirstTermAirman: false,
                  isOfficer: true,
                  verificationRequired: false,
                  location: '482 Cooper Greens',
                  office: 'Intranet',
                  pocName: 'Litzy Smith',
                  pocPhoneNumber: '1-412-529-2261 x57069',
                  pocEmail: 'Amina_Walker@hotmail.com',
                  createdAt: '2021-04-30T14:00:49.422Z',
                  updatedAt: '2021-04-30T14:00:49.422Z',
                },
                {
                  id: 27,
                  title: 'cupiditate laboriosam est labore animi',
                  text:
                    'expedita velit asperiores aliquam in natus dicta voluptas voluptatem similique excepturi et cum consequatur delectus dolore rerum unde cum enim ipsa architecto qui eligendi quia magnam omnis hic doloremque distinctio eos esse dolor numquam nostrum inventore veritatis ad soluta aspernatur culpa nostrum dolorem deserunt harum saepe asperiores voluptatem ipsa laboriosam',
                  categoryID: 4,
                  isFirstDutyStation: true,
                  isFirstTermAirman: true,
                  isOfficer: true,
                  verificationRequired: true,
                  location: '32082 Benny Pines',
                  office: 'Tactics',
                  pocName: 'Jed Keeling',
                  pocPhoneNumber: '(094) 406-8637 x06863',
                  pocEmail: 'Kayla_Moen@hotmail.com',
                  createdAt: '2021-04-30T14:00:49.562Z',
                  updatedAt: '2021-04-30T14:00:49.562Z',
                },
              ],
              id: 4,
              title: 'Hauck, Reichel and Bogan',
              ownerID: 9,
              createdAt: '2021-04-30T14:00:48.942Z',
              updatedAt: '2021-04-30T14:00:48.942Z',
            },
            {
              tasks: [
                {
                  id: 5,
                  title: 'asperiores reprehenderit laboriosam aliquid dolore',
                  text:
                    'qui labore deserunt commodi amet amet odio soluta eius nam beatae veritatis fuga fugit quia suscipit mollitia rem ut hic in autem pariatur ratione architecto voluptates minima dolor sint consequatur nihil fugiat dolorem ipsam ipsum quia aut aut voluptatem et deleniti est consectetur quasi consequatur ad eum occaecati dolores labore',
                  categoryID: 3,
                  isFirstDutyStation: true,
                  isFirstTermAirman: false,
                  isOfficer: true,
                  verificationRequired: false,
                  location: '9601 Ida Crossing',
                  office: 'Marketing',
                  pocName: 'Heloise Pouros',
                  pocPhoneNumber: '012.033.0272',
                  pocEmail: 'Kody56@gmail.com',
                  createdAt: '2021-04-30T14:00:49.153Z',
                  updatedAt: '2021-04-30T14:00:49.153Z',
                },
                {
                  id: 24,
                  title: 'recusandae et in laboriosam praesentium',
                  text:
                    'dolorem dolores ipsum eius adipisci quos molestiae laudantium et excepturi et mollitia aut et eaque est a commodi quod hic vel ea dolorum id perferendis voluptatem ab totam in qui quo dicta quis ut asperiores consequatur aut error occaecati aut aspernatur et vel aut vel rem delectus eos aliquam blanditiis',
                  categoryID: 3,
                  isFirstDutyStation: true,
                  isFirstTermAirman: true,
                  isOfficer: true,
                  verificationRequired: true,
                  location: '06613 Tromp Parkways',
                  office: 'Response',
                  pocName: "Loraine O'Hara",
                  pocPhoneNumber: '022-493-0293 x58144',
                  pocEmail: 'Blanche_Abshire@gmail.com',
                  createdAt: '2021-04-30T14:00:49.503Z',
                  updatedAt: '2021-04-30T14:00:49.503Z',
                },
              ],
              id: 3,
              title: "Marquardt, Durgan and O'Hara",
              ownerID: 10,
              createdAt: '2021-04-30T14:00:48.924Z',
              updatedAt: '2021-04-30T14:00:48.924Z',
            },
            {
              tasks: [
                {
                  id: 19,
                  title: 'ut rerum doloremque soluta qui',
                  text:
                    'qui placeat sunt aspernatur officiis molestiae id laudantium libero et sed voluptatem et illum reprehenderit est nobis sit laborum facere debitis fuga qui quibusdam sit neque exercitationem necessitatibus rem pariatur neque repellendus harum dolore eos libero rerum saepe voluptas tempore aliquam sit quae doloribus a minima facilis saepe tenetur quia',
                  categoryID: 6,
                  isFirstDutyStation: false,
                  isFirstTermAirman: true,
                  isOfficer: true,
                  verificationRequired: false,
                  location: '2914 Creola Rue',
                  office: 'Optimization',
                  pocName: 'Pete Halvorson',
                  pocPhoneNumber: '(577) 738-0979 x65921',
                  pocEmail: 'Melisa_Botsford64@gmail.com',
                  createdAt: '2021-04-30T14:00:49.392Z',
                  updatedAt: '2021-04-30T14:00:49.392Z',
                },
              ],
              id: 6,
              title: 'Hoeger LLC',
              ownerID: 10,
              createdAt: '2021-04-30T14:00:48.973Z',
              updatedAt: '2021-04-30T14:00:48.973Z',
            },
          ],
          status: 'idle',
        }}
        actions={{ toggleTaskForm: fn, setEditModeOff: fn }}
      />,
      container
    );
    fireEvent.click(screen.getByRole('button', { name: /close/i }));
    expect(fn).toHaveBeenCalledTimes(2);
  });
});
